[common]
platform = espressif32
framework = arduino
monitor_speed = 921600
lib_deps_shared =
	mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1
	adafruit/Adafruit SSD1306@^2.5.15
build_flags_shared =
	-D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
	-D CFG_us915
	-D CFG_sx1276_radio

[env:ttgo-lora32-v21]
board = ttgo-lora32-v21
platform = ${common.platform}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps_shared}
build_flags = ${common.build_flags_shared}

[env:ttgo-t-beam-v1]
board = ttgo-t-beam
platform = ${common.platform}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps_shared}
build_flags =
	${common.build_flags_shared}
	-D TBEAM_V1
