[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 921600
lib_deps =
	ModbusClient=https://github.com/eModbus/eModbus.git
	marvinroger/AsyncMqttClient@^0.9.0
	me-no-dev/AsyncTCP@^1.1.1
	bblanchon/ArduinoJson@^7.0.0
