[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 921600
lib_deps = 
	ModbusClient=https://github.com/eModbus/eModbus.git
	jgromes/RadioLib@^7.0.0
